version: '3.8'

services:
  cogitech-app:
    build: .
    ports:
      - '8080:80'
    restart: unless-stopped
    container_name: cogitech-recruitment-task
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  cogitech-dev:
    build:
      context: .
      target: build
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run dev --host 0.0.0.0
    environment:
      - NODE_ENV=development
    profiles:
      - dev
